trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'BankingApi/BankingApi.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: 'BankingApi/BankingApi.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureConnection'
    appName: 'bigpurplebankifysy3weuhd6k'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'